version: 2
aliases:

  - &build
    working_directory: /app
    docker:
      - image: singledigital/bay-circle:latest
        environment: &environment
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSE_PROJECT_NAME: mysite
          COMPOSE_FILE: docker-compose.yml
          INSTALL_SUGGEST: 0
          BEHAT_PROFILE: ""
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.06.0-ce
      - run:
          name: Composer validate
          # @dev
          command: composer validate --ansi --strict --no-check-all
      - run:
          name: Start containers
          command: |
            printenv
            echo "COMPOSE_FILE=$COMPOSE_FILE" >> .env.local
            echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env.local
            echo "GITHUB_PRIVATE_TOKEN=$GITHUB_PRIVATE_TOKEN" >> .env.local
            echo "BEHAT_PROFILE=$BEHAT_PROFILE" >> .env.local
            make docker-start
      - run:
          name: Copy files into container
          command: docker cp -L /app/. $(docker-compose ps -q cli):/app/
      - run:
          name: Install dev dependencies
          command: make install
      - run:
          name: Lint code
          command: make lint
      - run:
          name: Prepare test fixtures
          command: make install-site
      - run:
          name: Enable current module and dependencies
          command: make install-module
      - run:
          name: Run tests
          command: |
            make test-behat || make test-behat -- --rerun
      - run:
          name: Copy artifacts
          command: |
            mkdir -p /tmp/artifacts/behat
            docker cp $(docker-compose ps -q cli):/app/screenshots /tmp/artifacts/behat
          when: always
      - store_artifacts:
          path: /tmp/artifacts

jobs:
  build:
    <<: *build

  build_suggest:
    <<: *build
    docker:
      - image: singledigital/bay-circle:latest
        environment:
          <<: *environment
          INSTALL_SUGGEST: 1
          BEHAT_PROFILE: "--profile=suggest"

workflows:
  version: 2
  main:
    jobs:
      - build
      - build_suggest
